# Generated by Django 5.1 on 2024-08-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default='No description available'),
            preserve_default=False,
        ),
    ]
